spring:
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: cn.sichu.**.domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  configLocation: classpath:/mybatis-config.xml

logging:
  level:
    cn.sichu: debug
    org.springframework.boot.autoconfigure: warn
  config:
    classpath: logback-spring.xml