spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment_tool_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: cn.sichu.**.domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  configLocation: classpath:/mybatis-config.xml

server:
  port: 8889
  servlet:
    context-path: /
    tomcat:
      uri-encoding: UTF-8
      accept-count: 1000
      threads:
        max: 800
        min-spare: 100

logging:
  level:
    cn.sichu: debug
    org.springframework.boot.autoconfigure: warn
  config:
    classpath: logback-application.xml